version: '3'

services:
  jupyer-notebook-pyspark:
    image: jupyter/pyspark-notebook:spark-3.3.1
    ports:
      - '8888:8888'
      - '4040:4040'
    volumes:
      - ./data:/home/jovyan/work/data
      - ./jars:/home/jovyan/work/jars
      - ./jobs:/home/jovyan/work/jobs
      - ./notebooks:/home/jovyan/work/notebooks
    user: root
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=tad
    networks:
      - spark-network

  mariadb:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - "./config/mariadb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=data
    restart: on-failure
    networks:
      - spark-network

networks:
  spark-network:
    external: true
    driver: bridge
      
